# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use
# For example: application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

spring:
  application:
    name: user-service
  profiles:
    active: "@profiles.active@"
  lifecycle:
    timeout-per-shutdown-phase: 10s

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: false
    redis:
      enabled: false
